autoplatz/Models/TestDrive.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace autoplatz.Models
{
    public class TestDrive
    {
        public int TestDriveID { get; set; }
        public DateTime Date { get; set; }
        public bool IsApproved { get; set; }
        public int CarID { get; set; }
        public string ApplicationUserID{ get; set; }

        public Car Car { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

    }
}

autoplatz/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using autoplatz.Data;
using autoplatz.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Authorization;

namespace autoplatz.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        

        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        //


        // GET: Orders
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.ApplicationUser).Include(o => o.Car);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.ApplicationUser)
                .Include(o => o.Car)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Date,PaymentMethod,IsPaid,ApplicationUserID,CarID")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", order.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", order.CarID);
            return View(order);
        }


        // GET: Orders/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", order.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", order.CarID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,Date,PaymentMethod,IsPaid,ApplicationUserID,CarID")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", order.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", order.CarID);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.ApplicationUser)
                .Include(o => o.Car)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Order.FindAsync(id);
            _context.Order.Remove(order);
            Car car = _context.Car.Find(order.CarID);
            car.IsAvailable = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.OrderID == id);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Customer")]
        public IActionResult SaveOrder([Bind("OrderID,Date,PaymentMethod,IsPaid,ApplicationUserID,CarID")] Order order) {

            Car car = _context.Car.Find(order.CarID);
            car.IsAvailable = false;
            _context.Car.Update(car);
            _context.Order.Add(order);
            _context.SaveChanges();
            return RedirectToAction("MyOrders");

        }

        [Authorize(Roles = "Admin, Customer")]
        [HttpGet, ActionName("OrderCar")]
        public IActionResult OrderCar(int id) {
            Car Car = _context.Car.Find(id);
           
                ApplicationUser ApplicationUser = _context.Users.Find(userManager.GetUserId(HttpContext.User));

                Order order = new Order
                {
                    Date = DateTime.Now,
                    CarID = id,
                    Car = Car,
                    ApplicationUser = ApplicationUser,
                    ApplicationUserID = ApplicationUser.Id
                };

                return View(order);

        }

        [Authorize(Roles = "Admin, Customer")]
        public IActionResult MyOrders() {
            ApplicationUser ApplicationUser = _context.Users.Find(userManager.GetUserId(HttpContext.User));
            List<Order> paidOrders = _context.Order.Include(o=>o.Car).Where(o=>o.ApplicationUserID==ApplicationUser.Id && o.IsPaid==true).ToList();
            List<Order> unpaidOrders = _context.Order.Include(o => o.Car).Where(o => o.ApplicationUserID == ApplicationUser.Id && o.IsPaid == false).ToList();
            ViewData["PaidOrders"] = paidOrders as List<Order>;
            ViewData["UnpaidOrders"] = unpaidOrders as List<Order>;
            return View();
        }

        [Authorize(Roles = "Admin, Customer")]
        public IActionResult MyOrderDetails(int id) {
            Order order = _context.Order.Include(u=>u.ApplicationUser.Address.Country).Include(u=>u.Car).FirstOrDefault(o=>o.OrderID==id);
            return View(order);

        }
    }
}

autoplatz/Controllers/TestDrivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using autoplatz.Data;
using autoplatz.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace autoplatz.Controllers
{
    public class TestDrivesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;

        public TestDrivesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: TestDrives
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.TestDrive.Include(t => t.ApplicationUser).Include(t => t.Car);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: TestDrives/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testDrive = await _context.TestDrive
                .Include(t => t.ApplicationUser)
                .Include(t => t.Car)
                .FirstOrDefaultAsync(m => m.TestDriveID == id);
            if (testDrive == null)
            {
                return NotFound();
            }

            return View(testDrive);
        }

        // GET: TestDrives/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID");
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Customer")]
        public IActionResult Reserve(int id) {
            
                DateTime date = DateTime.Now.Date;
                Car Car = _context.Car.Find(id);
                ApplicationUser ApplicationUser = _context.Users.Find(userManager.GetUserId(HttpContext.User));
                TestDrive testDrive = new TestDrive
                {
                    CarID = id,
                    ApplicationUserID = userManager.GetUserId(HttpContext.User),
                    Car = Car,
                    ApplicationUser = ApplicationUser,
                    Date = DateTime.Parse(DateTime.Now.AddHours(2).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss"))

                };
                return View(testDrive);
           

        }

        // POST: TestDrives/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("TestDriveID,Date,IsApproved,CarID,ApplicationUserID")] TestDrive testDrive)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testDrive);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", testDrive.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", testDrive.CarID);
            return View(testDrive);
        }
        
        [HttpPost]
        [Authorize(Roles = "Admin, Customer")]
        public IActionResult SaveTestDrive([Bind("TestDriveID,Date,IsApproved,CarID,ApplicationUserID")] TestDrive testDrive) {
            _context.Add(testDrive);
            _context.SaveChanges();
            return RedirectToAction("MyTestDrives");
        }



        // GET: TestDrives/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testDrive = await _context.TestDrive.FindAsync(id);
            if (testDrive == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", testDrive.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", testDrive.CarID);
            return View(testDrive);
        }

        // POST: TestDrives/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("TestDriveID,Date,IsApproved,CarID,ApplicationUserID")] TestDrive testDrive)
        {
            if (id != testDrive.TestDriveID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testDrive);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestDriveExists(testDrive.TestDriveID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserID"] = new SelectList(_context.Users, "Id", "Id", testDrive.ApplicationUserID);
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", testDrive.CarID);
            return View(testDrive);
        }

        // GET: TestDrives/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testDrive = await _context.TestDrive
                .Include(t => t.ApplicationUser)
                .Include(t => t.Car)
                .FirstOrDefaultAsync(m => m.TestDriveID == id);
            if (testDrive == null)
            {
                return NotFound();
            }

            return View(testDrive);
        }

        // POST: TestDrives/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var testDrive = await _context.TestDrive.FindAsync(id);
            _context.TestDrive.Remove(testDrive);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestDriveExists(int id)
        {
            return _context.TestDrive.Any(e => e.TestDriveID == id);
        }

        [Authorize(Roles = "Admin, Customer")]
        public IActionResult MyTestDrives() {
            ApplicationUser ApplicationUser = _context.Users.Find(userManager.GetUserId(HttpContext.User));
            List<TestDrive> approvedTestDrives = _context.TestDrive.Include(t=>t.Car).Where(t => t.ApplicationUserID == ApplicationUser.Id && t.IsApproved==true).ToList();
            List<TestDrive> unapprovedTestDrives = _context.TestDrive.Include(t => t.Car).Where(t => t.ApplicationUserID == ApplicationUser.Id && t.IsApproved==false).ToList();
            ViewData["approvedTestDrives"] = approvedTestDrives as List<TestDrive>;
            ViewData["unapprovedTestDrives"] = unapprovedTestDrives as List<TestDrive>;
            return View();
        }

        [Authorize(Roles = "Admin,Customer")]
        public IActionResult MyTestDriveDetails(int id) {
            TestDrive testDrive = _context.TestDrive.Include(t=>t.Car).Include(t => t.ApplicationUser).Where(t=>t.TestDriveID== id).FirstOrDefault();
            return View(testDrive);

        }
    }

}

autoplatz/Views/TestDrives/Create.cshtml
@model autoplatz.Models.TestDrive

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TestDrive</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsApproved" /> @Html.DisplayNameFor(model => model.IsApproved)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class ="form-control" asp-items="ViewBag.CarID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserID" class="control-label"></label>
                <select asp-for="ApplicationUserID" class ="form-control" asp-items="ViewBag.ApplicationUserID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

autoplatz/Views/TestDrives/Delete.cshtml
@model autoplatz.Models.TestDrive

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TestDrive</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsApproved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TestDriveID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

autoplatz/Views/TestDrives/Details.cshtml
@model autoplatz.Models.TestDrive

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TestDrive</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsApproved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TestDriveID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

autoplatz/Views/TestDrives/Edit.cshtml
@model autoplatz.Models.TestDrive

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TestDrive</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TestDriveID" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsApproved" /> @Html.DisplayNameFor(model => model.IsApproved)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class="form-control" asp-items="ViewBag.CarID"></select>
                <span asp-validation-for="CarID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserID" class="control-label"></label>
                <select asp-for="ApplicationUserID" class="form-control" asp-items="ViewBag.ApplicationUserID"></select>
                <span asp-validation-for="ApplicationUserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

autoplatz/Views/TestDrives/Index.cshtml
@model IEnumerable<autoplatz.Models.TestDrive>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Is Approved
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Car)
            </th>
            <th>
               Full name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsApproved)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Car.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName) &nbsp;@Html.DisplayFor(modelItem => item.ApplicationUser.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TestDriveID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TestDriveID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TestDriveID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

autoplatz/Views/TestDrives/MyTestDriveDetails.cshtml
@model autoplatz.Models.TestDrive

@{
    ViewData["Title"] = "MyTestDriveDetails";
}

<h1>Order Details</h1>
<hr />
<div class="row">
    <div class="col-6">
        <h4>Test Drive</h4>
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class="col-sm-4">
                Is It Approved
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.IsApproved)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Car)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Car.Model)
            </dd>
            <dt class="col-sm-4">
                Full name
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ApplicationUser.FirstName)&nbsp;@Html.DisplayFor(model =>
model.ApplicationUser.LastName)
            </dd>
        </dl>
       
    </div>

    <div class="col-6">
        <br />
        <table class="table">
            <tbody>
                <tr class="row">
                    <td class="col-md-4">
                        <img class="broo" src="@Html.DisplayFor(modelItem => Model.Car.ImageUrl)" alt="car picture">
                    </td>
                    <td class="col-md-4">
                        <h3 class="align-top"><strong> @Html.DisplayFor(modelItem => Model.Car.Model)</strong></h3>
                        <hr />
                        <h4>Engine:</h4>
                        <h6>@Html.DisplayFor(modelItem => Model.Car.Engine)</h6>
                        <h4>Horsepower:</h4>
                        <h6>@Html.DisplayFor(modelItem => Model.Car.HorsePower)</h6>
                        <h4>Mileage:</h4>
                        <h6>@string.Format("{0:N0}", Model.Car.Mileage) km</h6>
                    </td>
                    <td class="col-md-4">
                        <h3 class="align-top"><strong>@string.Format("{0:N}", Model.Car.Price) &euro;</strong></h3>
                        <hr />
                        <h4>Model year:</h4>
                        <h6>@Html.DisplayFor(modelItem => Model.Car.HorsePower)</h6>
                        <h4>Color:</h4>
                        <h6>@Html.DisplayFor(modelItem => Model.Car.Color)</h6>
                        <hr />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div>
    <a asp-action="MyOrders" asp-controller="Orders">Back to List</a>
</div>

autoplatz/Views/TestDrives/MyTestDrives.cshtml
@model IEnumerable<autoplatz.Models.TestDrive>

@{
    ViewData["Title"] = "MyTestDrives";
    var approvedTestDrives = ViewData["approvedTestDrives"] as List<TestDrive>;
    var unapprovedTestDrives = ViewData["unapprovedTestDrives"] as List<TestDrive>;
}

<h1>My Test Drives</h1>


    <div class="row">
        <div class="col">
            <h2 class="text-center">Approved Test Drives</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Test Drive Date</th>
                        <th scope="col">Car model</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var test in approvedTestDrives)
                    {
                    <tr>
                        <td>@test.Date</td>
                        <td>@test.Car.Model</td>
                        <td><a asp-action="MyTestDriveDetails" asp-controller="TestDrives" asp-route-id="@test.TestDriveID">View details</a></td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>
        <div class="col">
            <h2 class="text-center">Unapproved Test Drives</h2>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Test Drive Date</th>
                        <th scope="col">Car model</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var test in unapprovedTestDrives)
                    {
                    <tr>
                        <td>@test.Date</td>
                        <td>@test.Car.Model</td>
                        <td><a asp-action="MyTestDriveDetails" asp-controller="TestDrives" asp-route-id="@test.TestDriveID">View details</a></td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>